### ISSUE TITLE
View package analysis just shows a json dump.

### ISSUE THREAD

**Issue by jdalton** [npms-io/npms-www#106]
When I click on the "View this package analysis" link it just shows a json dump:
https://api.npms.io/v2/package/lodash

<img width="100%" src="https://cloud.githubusercontent.com/assets/4303/18771286/8fd90ef0-80f2-11e6-997e-f3ebc923cb58.png">

**Comment by satazor** [comment]
@jdalton The final solution is to have a dedicated package page (e.g. https://npms.io/package/lodash) that will show the analysis data in a more human friendly way.
But for now, it's expected to simply open the API response in a new tab.

**Comment by jdalton** [comment]
Ok 😎
