### ISSUE TITLE
Email addresses are not being lowercased before hashing for Gravatar

### ISSUE THREAD

**Issue by TehShrike** [npms-io/npms-www#107]
The avatar that shows up on npms.io: 
![image](https://cloud.githubusercontent.com/assets/1141869/18961520/e9742838-8632-11e6-85d9-3b9b5826a6d3.png)

The avatar that shows up on npmjs.com: 
![image](https://cloud.githubusercontent.com/assets/1141869/18961560/03498122-8633-11e6-8575-f42becd85f33.png)

It looks like users who uploaded an avatar directly to npmjs.com are showing up correctly, but Gravatar users are showing up with generated avatar images.

**Comment by satazor** [comment]
The npm registry doesn't contain user documents. Having that said, is impossible to know the URL of the image uploaded through npm.

Let me know if there's a way to retrieve it without having to crawl their website.

**Comment by TehShrike** [comment]
To display a gravatar, all you need is the user's email address.  https://secure.gravatar.com/site/implement/hash/

**Comment by satazor** [comment]
We are using gravatar, my avatar is being displayed correctly through gravatar. Need to check whats wrong with yours.

**Comment by TehShrike** [comment]
Ah, I see what's happening.  The email address is not being lowercased before it is hashed.
- me@joshduff.com hashes to [b0d8ecb1f35283c9ac7fd219916efb90](https://www.gravatar.com/avatar/b0d8ecb1f35283c9ac7fd219916efb90?d=retro&r=g&s=40) (correct) 
- me@JoshDuff.com hashes to [8ad29570949de46ca2713534f9070ab3](https://www.gravatar.com/avatar/8ad29570949de46ca2713534f9070ab3?d=retro&r=g&s=40) (incorrect)

The former is what npmjs.com is displaying, the latter is what npms.io is displaying.

**Comment by satazor** [comment]
Hmm, acordingg to the RFC email is case sensitive, despite most mail servers and providers implement it as case insensitive. I suggest that you fix your emails in the package.json otherwise we could be breaking other gravatars by lowercasing.

**Comment by TehShrike** [comment]
Which RFC?  This has nothing to do with email address specifications, this is part of Gravatar's API.  When using Gravatar, you have to follow all three steps: https://secure.gravatar.com/site/implement/hash/

Right now, npms.io is not following the second step.

**Comment by satazor** [comment]
Fixed!
