### ISSUE TITLE
How can packages be prevented from indexing?

### ISSUE THREAD

**Issue by dandv** [npms-io/npms-www#112]
https://npms.io/search?q=influx unfairly lists the same package from tree.xie twice:
- influxdb-nodejs
- simple-influx

The latter was [renamed](https://www.npmjs.com/package/simple-influx) to the former, but both show up in searches.

**Comment by satazor** [comment]
We can ignore them in https://github.com/npms-io/npms-analyzer/blob/master/config/default.json5#L24 but if it's published on npm, it should be searchable in npms.

I also advise to deprecate the old package with `npm deprecate`. That will make the score lower.

**Comment by satazor** [comment]
Score is now lower: https://npms.io/search?q=simple-influx
