### ISSUE TITLE
Style links so they stand out

### ISSUE THREAD

**Issue by dandv** [npms-io/npms-www#129]
Quick, can you tell which of the words in this screenshot are hyperlinked?

![image](https://cloud.githubusercontent.com/assets/33569/20776385/095469ca-b715-11e6-933f-ffcf7aba934f.png)

**Comment by satazor** [comment]
You are right, not much specially on low contrast monitors. What if we underline?

**Comment by dandv** [comment]
Underlining or the [GitHub style](https://meteor.engineer) (maybe inverted, given the color scheme) would be a good idea.

It would also be great if visited links have a different color (by default purple).

**Comment by satazor** [comment]
I made all links a bit bolder instead. Being deployed right now. Thanks!
