### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by Lellansin** [npms-io/npms-www#140]
While I did *https://npms.io/search?q=koa*, I got `Oops, an error ocurred while fetching the results.`
Is there something wrong?

**Comment by Lellansin** [comment]
it works now

**Comment by satazor** [comment]
Maybe it was some temporary issue related to our hosting.

**Comment by abhishiv** [comment]
@satazor again seeing this error. Just for your information, this error often shows up since this week.

**Comment by satazor** [comment]
It's indeed related to our hosting. I have other machines for other projects and they are suffering the same.
