### ISSUE TITLE
npms.io site down

### ISSUE THREAD

**Issue by deepu105** [npms-io/npms-www#174]
npms.io seems to be down currently

**Comment by satazor** [comment]
I'm aware. The disk is full and I can't access the machine. Will try to recover. Alternatively I've asked npmjs to host the API and the badges API on their end.

Will update this issue when I got more info.

**Comment by deepu105** [comment]
I think if npmjs can host this that would be great and would reduce the pressure on you. keep up the good work

**Comment by satazor** [comment]
It has been fixed. Sorry for the inconvenience.

**Comment by deepu105** [comment]
Thanks a lot
