### ISSUE TITLE
Search within chromes address bar is broken

### ISSUE THREAD

**Issue by mrtnbroder** [npms-io/npms-www#177]
Whenever I want to use Chrome's search feature in the Adress Bar, I get 0 results, because the url transforms from

![screen shot 2017-07-14 at 14 13 05](https://user-images.githubusercontent.com/1118826/28211826-e889690c-689e-11e7-9fb1-8d0963004323.jpg)

to

`https://npms.io/search?term=ramda`

but npms.io uses

`https://npms.io/search?q=ramda`

Please 1. either allow `term` again or tell chrome to use `q` instead of `term`.

**Comment by satazor** [comment]
You should have a cached version of the search. Please remove it from the providers and clear the cache for the npms site.

See: https://github.com/npms-io/npms-www/blob/master/web/opensearch.xml#L8
