### ISSUE TITLE
npms.io search broken (

### ISSUE THREAD

**Issue by kroitor** [npms-io/npms-www#181]
Whatever I type in the search field it says *"Oops, an error ocurred while fetching the results"*.

<img width="848" alt="screen shot 2017-08-05 at 13 09 41" src="https://user-images.githubusercontent.com/1294454/28994797-764f92ec-79df-11e7-8074-d93fc51734cf.png">

**Comment by satazor** [comment]
Should be ok now, elasticsearch went down for some reason.

**Comment by kroitor** [comment]
P.S. there's a typo in the word 'occurred'
