### ISSUE TITLE
Support OpenSearch

### ISSUE THREAD

**Issue by sindresorhus** [npms-io/npms-www#2]
So I can just write npms+<kbd>Tab</kbd> in the URL bar to search npms directly from there.

Example:

``` html
<link title="Bower.io" type="application/opensearchdescription+xml" href="http://bower.io/opensearch.xml" rel="search">
```

http://bower.io/opensearch.xml

https://www.google.com/search?q=opensearch

**Comment by satazor** [comment]
Thanks we will do

**Comment by satazor** [comment]
@sindresorhus this was done in d5abe912d33358684b9fa01d89490941ca6ec1d3

Open search also supports JSON suggestions to be displayed as you type. Would that be something you would like or too intrusive?

**Comment by sindresorhus** [comment]
That would be very useful.

**Comment by satazor** [comment]
Ok I will open a new issue in the API: https://github.com/npms-io/npms-api/issues/4
