### ISSUE TITLE
wrong alarm

### ISSUE THREAD

**Issue by atian25** [npms-io/npms-www#208]
![image](https://user-images.githubusercontent.com/227713/33469295-060c9410-d69d-11e7-9e47-779dbf4f479e.png)

![image](https://user-images.githubusercontent.com/227713/33469304-11ac5cb0-d69d-11e7-8353-2faec84d37cc.png)

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/33469474-1828750a-d69e-11e7-9b78-59aa51a55e6a.png)

egg use `^` to import deps, and moment had release `'2.19.3': '2017-11-29T16:28:22.840Z'`

**Comment by satazor** [comment]
The package needs to be analyzed again for that to disappear. That happens when:

- a new version is published
- the analyzes becomes stale which happens each 15 days
