### ISSUE TITLE
Community reviews

### ISSUE THREAD

**Issue by MrDHat** [npms-io/npms-www#22]
Currently, the analyzer looks to help with determining the "relevance" of the module on the basis of Github activity. One step ahead would be to add a community driven review system for the modules.

Essentially, "amazon-like" star based reviews and comments. The main aim is to incorporate this into search results so that good modules show up higher than crappier ones. What do you guys think about this?

**Comment by satazor** [comment]
@MrDHat Ty for the suggestion but this is out of the scope of npms, at least for now.
