### ISSUE TITLE
Leaking package maintainer email to bots

### ISSUE THREAD

**Issue by ankurk91** [npms-io/npms-www#225]
Hi,
The website https://npms.io is leaking all package maintainer email addresses to bots.
It is visible to Google (try to search email address on google) and scrapping sites can scrap the email addresses to spam them.

![screenshot from 2018-07-14 11 08 16](https://user-images.githubusercontent.com/6111524/42721308-4b85003a-8756-11e8-9958-15da6062a195.png)
You can notice email address in image tag's `alt` attribute.

![screenshot from 2018-07-14 11 14 15](https://user-images.githubusercontent.com/6111524/42721360-1509c2f6-8757-11e8-9168-10a85c633888.png)

I know that npm requires to have a pubic email. But npm itself never expose it to pubic in that way.

**Comment by ankurk91** [comment]
I just noticed same issue
https://github.com/npms-io/npms-www/issues/214

**Comment by satazor** [comment]
It seems we can send the md5 of the email to the component instead of the email. Could you do a PR with this strategy? We can use the sparkmd5 package.
