### ISSUE TITLE
Search shows outdated versions compared with npmjs.com

### ISSUE THREAD

**Issue by TremayneChrist** [npms-io/npms-www#230]
[@juggle/resize-observer](https://npms.io/search?q=%40juggle%2Fresize-observer) is currently stuck at `2.0.3` and npm is showing `2.3.0`.

I see this is happening for other packages too:
- npms-io/npms#31
- npms-io/npms#34

**Comment by jpw** [comment]
We're having this problem too: https://npms.io/search?q=%40springernature%2Fglobal-context

Search says 2.1.0 but [2.2.0 was published on 2019-07-03](https://github.com/springernature/frontend-global-toolkit/blob/master/packages/global-context/HISTORY.md#220-2019-07-03)

Thanks for having a look.

**Comment by satazor** [comment]
I've triggered the analysis for the packages you guys mentioned. The analyser was stopped for two weeks since the machine was restarted abruptly.

The analysis is now running and slowly recovering.
