### ISSUE TITLE
Link to `Try it out`

### ISSUE THREAD

**Issue by giuseppeg** [npms-io/npms-www#25]
Hi there, great project!
It'd be nice to get a link to try packages out on tonicdev e.g. https://tonicdev.com/npm/lodash

**Comment by satazor** [comment]
@atduarte are you also addressing this with your small redesign of the search results?

**Comment by atduarte** [comment]
@satazor Yep :)

**Comment by satazor** [comment]
Also see #33, the "try in tonic" appears on hover.

**Comment by satazor** [comment]
A new deployment just landed with this feature.

**Comment by giuseppeg** [comment]
Aw that didn't take long! Thank you folks :)
