### ISSUE TITLE
Loading npms.io locally animates the closed-by-default menu

### ISSUE THREAD

**Issue by mitchhentges** [npms-io/npms-www#27]
When the page is opened, the white "morph" effect plays for closing the menu on the right, despite the fact that the menu was never opened.

EDIT: This appears to only occur when developing locally: `localhost:8080`, but not on the live site: `npms.io`

**Comment by satazor** [comment]
Yes that's normal.. and I don't know what to do to avoid it. If you want to preview the built version run `npm run build && npm run serve -- --env prod`
