### ISSUE TITLE
Scroll to top doesn't work in Firefox 47.0

### ISSUE THREAD

**Issue by mocanew** [npms-io/npms-www#32]
I don't know if it's related to the issue, but I get this warning in the console: "This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!"

**Comment by satazor** [comment]
Deployed.
