### ISSUE TITLE
Node toolbox

### ISSUE THREAD

**Issue by stereobooster** [npms-io/npms-www#39]
Like  [ruby-toolbox](https://www.ruby-toolbox.com/), but for node (npm).

See also:
- http://stackoverflow.com/questions/30079465/cannot-find-equivalent-of-ruby-toolbox-for-javascript-libraries
- https://github.com/activesphere/nodetoolbox
- http://artandlogic.com/2013/07/the-javascript-toolbox/

**Comment by satazor** [comment]
@stereobooster I think this is out of the scope for this project, at least for now. Also there's http://bestof.js.org/ from @michaelrambeau, check it out!
