### ISSUE TITLE
(Suggestion) Back with menu open should close the menu

### ISSUE THREAD

**Issue by boogie666** [npms-io/npms-www#42]
Hi there, nice UI, clean and simple, just the way i like it :)

Is it possible to have the back button (browser back i mean) close the menu if it's open.
I believe that this would be better, especially on mobile where the natural instinct is to press the back button to get out of stuff.

Currently back does history back in all cases.

I would be more then happy to fix this myself :) if it is something that's wanted.

Cheers,
Boogie

**Comment by satazor** [comment]
The back button navigates to the previous URL, so to make this work we would have to add a /menu root which feels weird. I do not see other solution to implement what you want.

**Comment by satazor** [comment]
If you find another solution let me know, closing this for now.
