### ISSUE TITLE
Auto-complete/suggestion for search?

### ISSUE THREAD

**Issue by sarbbottam** [npms-io/npms-www#44]
It would be great to have auto-complete/suggestion features for the search, similar to what https://www.npmjs.com/ does. Thanks!

<img width="920" alt="screen shot 2016-06-27 at 7 56 14 am" src="https://cloud.githubusercontent.com/assets/949380/16384126/b1138546-3c3c-11e6-80d2-51f3310a7330.png">

**Comment by satazor** [comment]
Yep! We will add auto-complete soon.

**Comment by satazor** [comment]
#49
