### ISSUE TITLE
Website needs a favicon

### ISSUE THREAD

**Issue by revelt** [npms-io/npms-www#57]
Of course, issue is blocked by #15 because it's unclear what to put there.

**Comment by leo** [comment]
We also need an `apple-touch-icon`, a `twitter:image` and a `mask-icon` for Safari.

**Comment by satazor** [comment]
Yep.. If you guys have any friend which can design the logo and identity please reach them.

**Comment by leo** [comment]
@satazor What about using npm's "font"? In turn, I also think we should adjust the whole branding (the colors, etc.) to match npm's branding.

**Comment by revelt** [comment]
Yeah, something similar but not identical, so as not to break laws.. Anything square shaped is instantly recognisable as npm-related

**Comment by leo** [comment]
[Hmmm](https://www.npmjs.com/policies/trademark#the-npm-trademark-policy)

**Comment by satazor** [comment]
I will close this in favor of #15
