### ISSUE TITLE
Autofocus the input

### ISSUE THREAD

**Issue by IonicaBizau** [npms-io/npms-www#73]
It would be amazing if you autofocus the search input. 😁 Then we wouldn't have to click on that input.

Thanks for amazing product!

**Comment by satazor** [comment]
You actually don't need to focus the input, you can start typing right away similarly to google.com. We can autofocus the input on mobile devices.

**Comment by IonicaBizau** [comment]
@satazor Ah, nice! But it isn't very intuitive, tho...

**Comment by IonicaBizau** [comment]
Is there any specific reason why you wouldn't focus the input on desktop?

**Comment by satazor** [comment]
@IonicaBizau not really, it was decided to imitate google so that we have a standard behavior cross platform. Still, I'm open to auto-focus only in desktop.

//cc @atduarte

**Comment by IonicaBizau** [comment]
@satazor But Google does autofocus the search thingy.

**Comment by satazor** [comment]
@IonicaBizau indeed it does! Could you please update #61 so that it only `.focus()` in desktop? You will need to find a good library to detect desktop/mobile; you may use https://npms.io for that ahahah :)

**Comment by satazor** [comment]
@IonicaBizau I didn't noticed that #61 wasn't yours! Would you willing to do a PR to do auto-focus only on desktop?

**Comment by IonicaBizau** [comment]
@satazor Done. 😁

**Comment by IonicaBizau** [comment]
@satazor It seems you have a couple of [nice projects too](https://github.com/IonicaBizau/made-in-portugal). 😄

**Comment by satazor** [comment]
@IonicaBizau I mainly create my projects in https://github.com/IndigoUnited, these are all portuguese projects :)
