### ISSUE TITLE
[idea] Clickable tags

### ISSUE THREAD

**Issue by Delapouite** [npms-io/npms-www#82]
Currently tags displayed on result pages are unclickable.

I propose that when clicking on a tag, it should triggers a new search with this word.

**Comment by satazor** [comment]
Sounds ok to me, @atduarte ?

**Comment by atduarte** [comment]
SGTM

**Comment by satazor** [comment]
@Delapouite Could you please make a PR that adds this feature?

**Comment by Delapouite** [comment]
Sure. Here it is : https://github.com/npms-io/npms-www/pull/93

**Comment by satazor** [comment]
Deployed!
