### ISSUE TITLE
Displayed package version is inaccurate

### ISSUE THREAD

**Issue by shssoichiro** [npms-io/npms-www#96]
The version number that displays on the search results for a package is inaccurate (possibly cached server-side?). For example, the version number displayed for `angular-ui-boostrap` is 2.0.1, which was released on 2016-08-02. The latest version of this package on npm is 2.1.3, which was released 2016-08-25.

![screen shot 2016-09-12 at 9 04 22 am](https://cloud.githubusercontent.com/assets/5951392/18436811/298111ca-78c8-11e6-8410-c24daf2ccb66.png)

**Comment by satazor** [comment]
Hmm it seems that the npm registry that is being replicated is out of date for that package, but it says replication is ok.. need to investigate.

Thanks for the heads up.

**Comment by satazor** [comment]
I will stop the analyzer for now and re-replicate the npm registry. This will take a while.

**Comment by satazor** [comment]
@shssoichiro after the replication is done, I will re-activate the analyzer but the cached modules will only be re-analyzed in 15 days max or if they get updated. If you wish some of them to be analyzed right away please list them and I will manually trigger the analysis.

**Comment by satazor** [comment]
Done!

**Comment by Den-dp** [comment]
@satazor Same here 

![image](https://cloud.githubusercontent.com/assets/1770529/18450422/a0129368-793b-11e6-8246-074f831635b0.png)

So, as I understand this will be fixed by itself in ~15 days, right?

**Comment by satazor** [comment]
Correct! Or if the module gets published with a new version.

This was a weird couchdb rellication issue..

**Comment by satazor** [comment]
Actually staring the module in npmjs will also cause it to re-analyze (haven't tested, I'm on the phone.
